# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180206_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.URLField(default='', max_length=100, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
