# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_to_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_to_learn',
            field=models.CharField(default='', max_length=300, verbose_name='\u5b66\u5230\u4ec0\u4e48'),
        ),
    ]
