# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180201_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='nick_name',
        ),
    ]
